name: "Setup HarmonyOS SDK for Mac"
description: "Set up the latest version of the HarmonyOS SDK and add the command-line tools to the PATH"
author: "jiwangyihao"

# Define your outputs here.
outputs:
  sdk-path:
    description: 'The path of installed sdk'

runs:
  using: node20
  main: dist/index.js
